### ISSUE TITLE
Confirmation on leaving unsaved edits in any menu

### ISSUE THREAD

**Issue by ankurshaswat** [devclub-iitd/Yearbook#57]

**Comment by Atishya-jain** [comment]
Before changing the tab or closing the browser tab, check if there is any unsaved info that needs to be posted on backend. If yes, put up a warning message

**Comment by Atishya-jain** [comment]
@sohamvg in this will it ask a warning if we switch a tab everytime or only if there are unsaved edits?

**Comment by sohamvg** [comment]
Only if there are unsaved edits (i.e. if tab is closed).

**Comment by ankurshaswat** [comment]
Have you tested this?
And the issue was regarding internal tabs that are defined in website too. Like changing from profile to polls and other internal tabs.

**Comment by sohamvg** [comment]
Yes, I have tested. Works for both internal & external tabs.
